#!/usr/bin/env python3
"""Expand codes.db with brand-specific codes for underrepresented brands."""
import sqlite3, json, os

DB = os.path.join(os.path.dirname(__file__), "codes.db")

# Format: (code, brand, severity, title_en, title_fr, causes_fr, steps_fr)
NEW_CODES = [

# ═══════════════════════════════════════════════════════════════════════════
# PEUGEOT / CITROËN (PSA) — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","PEUGEOT","medium","MAF sensor intermittent","Débitmètre air — signal intermittent",
 '["Débitmètre encrassé","Connexion électrique lâche","Filtre à air colmaté"]',
 '["Nettoyer le débitmètre à l\'IPA.","Vérifier connecteur et masse.","Remplacer le filtre à air."]'),
("P1110","PEUGEOT","medium","MAF sensor low input","Débitmètre air — signal faible",
 '["Débitmètre HS","Court-circuit masse","Alimentation 5V absente"]',
 '["Vérifier tension 5V sur le capteur.","Tester le débitmètre (valeurs 0-5V).","Remplacer si signal fixe <0,5V."]'),
("P1120","PEUGEOT","medium","Throttle position sensor low","Capteur position papillon — signal faible",
 '["Capteur TPS encrassé ou HS","Câblage endommagé","Corps papillon défectueux"]',
 '["Nettoyer le corps papillon.","Vérifier signal TPS (0,5-4,5V).","Remplacer le capteur TPS si nécessaire."]'),
("P1130","PEUGEOT","medium","O2 sensor circuit malfunction bank 1","Sonde lambda amont — circuit défaillant B1",
 '["Sonde lambda encrassée ou HS","Fuite d\'échappement avant sonde","Câblage sonde coupé"]',
 '["Inspecter le circuit d\'échappement.","Vérifier tension chauffage sonde (12V).","Remplacer la sonde lambda amont."]'),
("P1160","PEUGEOT","high","Injector circuit malfunction","Circuit injecteur — défaut général",
 '["Injecteur bouché ou HS","Relais injection défectueux","Câblage injecteur endommagé"]',
 '["Tester chaque injecteur (résistance 14-16Ω).","Vérifier alimentation calculateur.","Procéder au nettoyage ultrasons si bouché."]'),
("P1175","PEUGEOT","high","Fuel system rich bank 1","Mélange trop riche — B1",
 '["Injecteurs qui fuient","Pression carburant excessive","Sonde O2 défectueuse"]',
 '["Contrôler la pression carburant au ralenti.","Tester les fuites injecteurs (bougies noires).","Vérifier signal sonde O2 amont."]'),
("P1176","PEUGEOT","high","Fuel system lean bank 1","Mélange trop pauvre — B1",
 '["Fuite d\'air après débitmètre","Pompe carburant faible","Injecteur(s) bouché(s)"]',
 '["Vérifier durites et joints après le débitmètre.","Mesurer pression carburant (3 bar min).","Tester débit injecteurs."]'),
("P1225","PEUGEOT","high","Throttle control — closed position","Papillon — position fermée défaillante",
 '["Ressort de rappel du papillon cassé","Motorisation papillon HS","Corps papillon grippé"]',
 '["Effectuer la réinitialisation du papillon.","Nettoyer le corps papillon.","Remplacer le corps papillon électronique si grippé."]'),
("P1336","PEUGEOT","high","Crankshaft/camshaft signal mismatch","Signal vilebrequin/arbre à cames — incohérence",
 '["Courroie/chaîne de distribution sautée","Capteur PMH défectueux","Cible de vilebrequin endommagée"]',
 '["Vérifier calage distribution.","Inspecter la cible et le capteur PMH.","Contrôler jeu de la chaîne de distribution."]'),
("P1337","PEUGEOT","high","Crankshaft position signal missing","Signal capteur vilebrequin absent",
 '["Capteur PMH HS ou trop éloigné","Cible magnétique endommagée","Câblage coupé"]',
 '["Vérifier entrefer capteur PMH (0,8-1,2mm).","Tester la résistance capteur (900-1100Ω).","Inspecter la cible de vilebrequin."]'),
("P1340","PEUGEOT","high","Camshaft/crankshaft timing error","Calage distribution — erreur synchronisation",
 '["Chaîne de distribution allongée (EP6)","Actuateur VVT défectueux","Huile moteur dégradée"]',
 '["Changer l\'huile moteur (5W30 PSA).","Vérifier la chaîne de distribution.","Tester l\'actuateur VVT."]'),
("P1351","PEUGEOT","medium","Ignition coil A primary circuit","Bobine d\'allumage A — circuit primaire",
 '["Bobine claquée","Câblage endommagé","Module allumage HS"]',
 '["Permuter les bobines pour isoler la défaillante.","Mesurer résistance primaire (0,3-1Ω).","Remplacer la bobine défectueuse."]'),
("P1400","PEUGEOT","medium","EGR valve flow insufficient","Valve EGR — débit insuffisant",
 '["Valve EGR encrassée ou coincée fermée","Durite EGR bouchée","Capteur différentiel pression HS"]',
 '["Nettoyer la valve EGR (décapage).","Vérifier les durites de pression différentielle.","Tester l\'actionneur EGR (PWM)."]'),
("P1401","PEUGEOT","medium","EGR valve flow excessive","Valve EGR — débit excessif",
 '["Valve EGR coincée ouverte","Joint de valve EGR endommagé"]',
 '["Inspecter et nettoyer la valve EGR.","Vérifier l\'étanchéité du joint.","Remplacer la valve si coincée."]'),
("P1437","PEUGEOT","medium","EVAP emission control — leak","Dépollution EVAP — fuite détectée",
 '["Bouchon de réservoir mal fermé","Durite charbon actif fendue","Electrovanne purge HS"]',
 '["Vérifier le bouchon de réservoir.","Inspecter les durites d\'évent.","Tester l\'électrovanne de purge."]'),
("P1441","PEUGEOT","medium","EVAP purge valve stuck open","Electrovanne purge EVAP — coincée ouverte",
 '["Electrovanne collée ouverte","Durite de dépression percée","Calculateur HS"]',
 '["Tester l\'électrovanne (résistance 22-30Ω).","Vérifier la dépression sur la durite.","Remplacer l\'électrovanne si défaillante."]'),
("P1614","PEUGEOT","high","Immobiliser code incorrect","Antidémarrage — code incorrect",
 '["Télécommande ou badge non appris","Calculateur moteur changé sans adaptation","BSI défaillante"]',
 '["Procéder à l\'apprentissage clé (Diagbox).","Vérifier communication BSI/calculateur.","Contacter un concessionnaire PSA."]'),
("P1615","PEUGEOT","high","Immobiliser EEPROM error","Antidémarrage — erreur EEPROM",
 '["Mémoire BSI corrompue","Batterie déchargée lors d\'une écriture","Intervention calculateur non conforme"]',
 '["Recharger la batterie.","Reconfigurer la BSI.","Intervention PSA nécessaire."]'),
("P1631","PEUGEOT","high","Engine immobiliser active","Antidémarrage actif — démarrage impossible",
 '["Clé non reconnue","BSI non synchronisée avec le calculateur","Panne réseau CAN"]',
 '["Tester une clé de secours.","Vérifier le bus CAN (U0001).","Synchroniser BSI et calculateur moteur."]'),
("P1717","PEUGEOT","medium","Gear selector switch — circuit fault","Commutateur sélecteur boîte — défaut circuit",
 '["Commutateur de vitesses HS","Câblage boîte endommagé","Calculateur BVA défaillant"]',
 '["Vérifier la position du sélecteur.","Tester le commutateur.","Diagnostiquer le calculateur BVA."]'),
("P1888","PEUGEOT","medium","Gearbox oil temperature high","Température huile boîte trop élevée",
 '["Huile boîte dégradée ou niveau bas","Radiateur huile bouché","Usage intensif en ville"]',
 '["Vérifier le niveau d\'huile de boîte.","Changer l\'huile boîte (recommandé 60 000 km).","Inspecter le radiateur huile."]'),

# ═══════════════════════════════════════════════════════════════════════════
# RENAULT — codes spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","RENAULT","medium","Mass air flow sensor intermittent","Débitmètre — signal intermittent",
 '["Débitmètre encrassé","Filtre à air colmaté","Connecteur lâche"]',
 '["Nettoyer le débitmètre.","Remplacer le filtre à air.","Vérifier le connecteur."]'),
("P1105","RENAULT","medium","Manifold absolute pressure sensor","Capteur pression absolue — défaut",
 '["Capteur MAP HS","Durite de dépression fissurée","Calculateur défaillant"]',
 '["Inspecter les durites.","Tester le capteur MAP (0-5V).","Remplacer si valeurs aberrantes."]'),
("P1120","RENAULT","medium","Accelerator pedal position sensor 1 low","Capteur pédale accélérateur 1 — signal faible",
 '["Capteur pedalier HS","Câblage endommagé sous le tableau de bord","Pédalier souillé"]',
 '["Nettoyer les connecteurs du pédalier.","Vérifier signal (0,5-4,5V).","Remplacer le capteur pédalier."]'),
("P1121","RENAULT","medium","Accelerator pedal position sensor 1 high","Capteur pédale accélérateur 1 — signal élevé",
 '["Court-circuit alimentation","Capteur HS","Calculateur défaillant"]',
 '["Vérifier l\'alimentation 5V.","Tester la résistance interne capteur.","Remplacer le capteur si HS."]'),
("P1125","RENAULT","high","Accelerator pedal sensor plausibility","Capteur pédale accélérateur — incohérence signal",
 '["Pédalier défaillant","Câblage endommagé","Calculateur moteur HS"]',
 '["Vérifier les deux pistes du pédalier.","Contrôler le câblage complet.","Tester avec un pédalier neuf."]'),
("P1130","RENAULT","medium","O2 sensor slow response bank 1","Sonde lambda — réponse lente B1",
 '["Sonde lambda empoisonnée","Carburant de mauvaise qualité","Fuite d\'air admission"]',
 '["Vérifier les oscillations O2 (correctes = >0,5V maxi mini).","Contrôler les fuites.","Remplacer la sonde lambda."]'),
("P1200","RENAULT","high","Injector control circuit fault","Circuit de commande injecteurs — défaut",
 '["Relais injection HS","Câblage injecteurs coupé","Calculateur défaillant"]',
 '["Vérifier le relais injection (bobine et contacts).","Tester l\'alimentation calculateur (pin 87).","Contrôler chaque câble injecteur."]'),
("P1225","RENAULT","high","Throttle body position error","Corps papillon — erreur de position",
 '["Ressort de rappel cassé","Motorisation papillon HS","Corps papillon encrassé"]',
 '["Réinitialiser le papillon (Contact off/on x3).","Nettoyer le corps papillon.","Remplacer le corps papillon."]'),
("P1230","RENAULT","high","Fuel pump relay circuit","Relais pompe à carburant — défaut circuit",
 '["Relais pompe HS","Fusible pompe claqué","Câblage endommagé"]',
 '["Vérifier le fusible pompe.","Tester le relais pompe (bobine 70-100Ω).","Contrôler l\'alimentation pompe (+12V)."]'),
("P1235","RENAULT","high","Fuel pump control out of range","Commande pompe carburant — hors plage",
 '["Pompe carburant en fin de vie","Filtre à carburant colmaté","Calculateur UC défaillant"]',
 '["Mesurer la pression carburant.","Remplacer le filtre carburant.","Tester le débit de la pompe."]'),
("P1337","RENAULT","high","Crankshaft sensor signal lost","Signal capteur vilebrequin perdu",
 '["Capteur PMH HS","Roue phonique endommagée","Câblage coupé"]',
 '["Vérifier l\'entrefer (1mm max).","Contrôler la résistance (200-900Ω).","Inspecter la roue phonique."]'),
("P1340","RENAULT","high","Camshaft/crankshaft correlation error","Erreur corrélation arbre à cames/vilebrequin",
 '["Courroie de distribution sautée","Capteur arbre à cames HS","Calculateur défaillant"]',
 '["Vérifier le calage distribution.","Tester les capteurs PMH et arbre à cames.","Rechercher fuite huile vers capteur."]'),
("P1380","RENAULT","medium","EGR solenoid valve circuit","Electrovanne EGR — défaut circuit",
 '["Electrovanne EGR encrassée","Câblage interrompu","Calculateur moteur HS"]',
 '["Vérifier l\'alimentation électrovanne (12V).","Nettoyer ou remplacer l\'électrovanne.","Contrôler le câblage."]'),
("P1400","RENAULT","medium","EGR valve insufficient flow","Vanne EGR — débit insuffisant",
 '["Vanne EGR encrassée au carbone","Durite de commande percée","Capteur pression différentielle HS"]',
 '["Nettoyer la vanne EGR.","Vérifier les durites pneumatiques.","Tester le capteur de pression différentielle."]'),
("P1500","RENAULT","medium","Vehicle speed sensor circuit","Capteur vitesse véhicule — défaut circuit",
 '["Capteur de vitesse HS","Câblage ABS endommagé","Calculateur ABS HS"]',
 '["Vérifier les connecteurs ABS.","Tester le signal capteur VSS.","Diagnostiquer le calculateur ABS."]'),
("P1600","RENAULT","high","ECU power supply low","Alimentation calculateur moteur — tension faible",
 '["Batterie faible ou défaillante","Mauvaise masse carrosserie","Alternateur HS"]',
 '["Mesurer la tension batterie (>12,4V repos).","Vérifier les masses calculateur.","Tester l\'alternateur (13,8-14,4V en marche)."]'),
("P1610","RENAULT","high","Immobiliser received wrong code","Antidémarrage — code erroné reçu",
 '["Clé non programmée","UCH/BCM défaillante","Interférence avec autre système"]',
 '["Utiliser la clé de secours.","Vérifier communication UCH/calculateur.","Reprogrammer les clés si nécessaire."]'),
("P1615","RENAULT","high","Immobiliser ECU fault","Antidémarrage — défaut UCH",
 '["UCH défaillante","Batterie déchargée pendant programmation","Calculateur incompatible"]',
 '["Vérifier l\'alimentation UCH.","Contrôler le bus réseau CAN/VAN.","Intervention Renault nécessaire."]'),
("P1760","RENAULT","medium","EGR position sensor fault","Capteur position EGR — défaut",
 '["Capteur EGR HS","Calamine sur axe EGR","Câblage endommagé"]',
 '["Nettoyer l\'axe de la vanne EGR.","Vérifier signal capteur (0-5V).","Remplacer si valeurs fixes."]'),
("P1900","RENAULT","medium","Gearbox — CAN communication fault","Boîte de vitesses — défaut communication CAN",
 '["Bus CAN boîte interrompu","Calculateur BVA HS","Connecteur boîte endommagé"]',
 '["Vérifier le câblage CAN boîte.","Tester la résistance CAN (120Ω).","Diagnostiquer le calculateur BVA."]'),

# ═══════════════════════════════════════════════════════════════════════════
# MERCEDES-BENZ — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1000","MERCEDES","low","OBD monitoring not complete","Surveillance OBD incomplète",
 '["Batterie récemment déconnectée","Cycle de conduite incomplet","Calculateur remplacé récemment"]',
 '["Effectuer un cycle de conduite complet (autoroute + ville).","Attendre extinction du voyant.","Vérifier qu\'aucun autre code n\'est présent."]'),
("P1100","MERCEDES","medium","MAF circuit intermittent","Débitmètre — circuit intermittent",
 '["Débitmètre HS ou encrassé","Connecteur desserré","Filtre à air saturé"]',
 '["Nettoyer le débitmètre (IPA).","Vérifier le connecteur 5 broches.","Remplacer le filtre à air."]'),
("P1128","MERCEDES","medium","Long term fuel trim system too lean","Apprentissage injection — mélange trop pauvre",
 '["Fuite d\'air sur tubulure admission","Débitmètre encrassé","Injecteurs partiellement bouchés"]',
 '["Inspecter les durites d\'admission.","Nettoyer le débitmètre.","Vérifier pression carburant."]'),
("P1130","MERCEDES","medium","Upstream O2 sensor signal range","Sonde lambda amont — hors plage",
 '["Sonde lambda encrassée","Fuite échappement amont","Carburant contaminé"]',
 '["Inspecter l\'échappement avant la sonde.","Vérifier oscillations sonde (0,1-0,9V).","Remplacer la sonde lambda amont."]'),
("P1140","MERCEDES","medium","Load signal out of range","Signal charge moteur — hors plage",
 '["Débitmètre défectueux","Calculateur HS","Prise de masse défaillante"]',
 '["Vérifier l\'étalonnage du débitmètre.","Contrôler les masses moteur.","Diagnostiquer le calculateur ME/SIM."]'),
("P1171","MERCEDES","high","Fuel system lean shift bank 1","Correction richesse en limite — B1 pauvre",
 '["Injecteurs usés","Pompe carburant faible","Filtre carburant colmaté"]',
 '["Mesurer la pression carburant (au moins 3,5 bar).","Nettoyer ou remplacer les injecteurs.","Remplacer le filtre carburant."]'),
("P1172","MERCEDES","high","Fuel system lean shift bank 2","Correction richesse en limite — B2 pauvre",
 '["Fuite air admission côté B2","Injecteurs B2 usés","Sonde O2 B2 HS"]',
 '["Inspecter l\'admission côté B2.","Tester les injecteurs B2.","Vérifier la sonde B2."]'),
("P1210","MERCEDES","high","Injection quantity adjustment","Ajustement quantité injection — hors plage",
 '["Pompe injection HS","Rail carburant en fuite","Régulateur de pression HS"]',
 '["Mesurer pression rail (démarrage 200-250 bar CDI).","Vérifier le débit de la pompe haute pression.","Contrôler les injecteurs piézo."]'),
("P1316","MERCEDES","high","Injector circuit fault cylinder 1","Circuit injecteur — cylindre 1 défaut",
 '["Injecteur C1 HS","Câblage injecteur C1 coupé","Calculateur défaillant"]',
 '["Tester la résistance de l\'injecteur C1 (CDI: 0,5Ω, essence: 15Ω).","Vérifier l\'alimentation.","Remplacer l\'injecteur si HS."]'),
("P1400","MERCEDES","medium","EGR valve control circuit","Vanne EGR — circuit de commande",
 '["Electrovanne EGR HS","Câblage interrompu","Calculateur défaillant"]',
 '["Tester la résistance électrovanne EGR.","Vérifier l\'alimentation (12V contact).","Contrôler le signal PWM."]'),
("P1410","MERCEDES","medium","Secondary air injection circuit","Injection d\'air secondaire — défaut circuit",
 '["Pompe d\'air secondaire HS","Electrovanne de commande HS","Clapet de non-retour bloqué"]',
 '["Tester la pompe d\'air (12V direct).","Vérifier le clapet antiretour.","Contrôler l\'électrovanne."]'),
("P1472","MERCEDES","medium","EVAP small leak detected","EVAP — petite fuite détectée",
 '["Joint de bouchon réservoir usé","Durite charbon actif fissurée","Electrovanne purge HS"]',
 '["Vérifier le bouchon réservoir.","Inspecter les durites.","Tester l\'électrovanne purge."]'),
("P1481","MERCEDES","medium","Cooling fan speed signal","Vitesse ventilateur refroidissement — signal",
 '["Ventilateur visceux HS","Embrayage visceux gripé","Capteur vitesse ventilateur HS"]',
 '["Vérifier la vitesse ventilateur à chaud.","Contrôler l\'embrayage visceux.","Remplacer si ventilateur ne s\'accélère pas."]'),
("P1600","MERCEDES","high","ECU power supply fault","Alimentation calculateur — défaut",
 '["Fusible principal calculateur claqué","Relais calculateur HS","Câblage alimentation coupé"]',
 '["Vérifier les fusibles boîtier moteur (F10/F11).","Tester le relais principale calculateur.","Contrôler masse calculateur."]'),
("P1634","MERCEDES","high","Immobiliser challenge response error","Antidémarrage — erreur défi/réponse",
 '["Clé transponder HS","EIS (module contact) défaillant","Câblage EIS/calculateur endommagé"]',
 '["Tester avec une autre clé.","Vérifier communication EIS/ME.","Reprogrammer le transponder."]'),
("P1680","MERCEDES","high","Throttle control motor circuit","Moteur papillon — défaut circuit",
 '["Motorisation papillon HS","Câblage moteur papillon endommagé","Calculateur ME défaillant"]',
 '["Nettoyer et lubrifier le corps papillon.","Tester la résistance moteur (1,5-3Ω).","Remplacer le corps papillon électronique."]'),
("P1800","MERCEDES","medium","Transmission range sensor fault","Capteur plage boîte de vitesses — défaut",
 '["Capteur position sélecteur HS","Câblage endommagé","Calculateur BVA défaillant"]',
 '["Vérifier la position sélecteur (PRND).","Tester les résistances capteur.","Diagnostiquer le calculateur EGS."]'),

# ═══════════════════════════════════════════════════════════════════════════
# TOYOTA / LEXUS — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","TOYOTA","medium","BARO sensor circuit","Capteur pression barométrique — défaut circuit",
 '["Capteur BARO intégré calculateur HS","Câblage calculateur endommagé"]',
 '["Vérifier tension 5V sur le capteur.","Remplacer le calculateur si le capteur est interne."]'),
("P1120","TOYOTA","medium","Accelerator pedal position sensor circuit","Capteur pédale accélérateur — circuit",
 '["Capteur pédale HS","Câblage sous tablier endommagé","Calculateur défaillant"]',
 '["Vérifier signal potentiomètre (0,5-4,5V).","Inspecter le câblage pédalier.","Remplacer le capteur pédale."]'),
("P1125","TOYOTA","high","Throttle control motor circuit","Moteur de commande papillon — circuit",
 '["Motorisation papillon HS","Corps papillon encrassé","Calculateur ECM HS"]',
 '["Nettoyer le corps papillon.","Tester la résistance du moteur (1,5-3Ω).","Effectuer l\'initialisation papillon."]'),
("P1130","TOYOTA","medium","Air-fuel ratio sensor circuit range","Capteur A/F — hors plage B1 S1",
 '["Capteur A/F encrassé","Fuite collecteur avant sonde","Câblage capteur endommagé"]',
 '["Vérifier l\'étanchéité du collecteur.","Tester la résistance capteur (10-40Ω).","Remplacer le capteur A/F si HS."]'),
("P1133","TOYOTA","medium","A/F sensor slow response bank 1","Capteur A/F — réponse lente B1",
 '["Capteur A/F en fin de vie","Carburant de mauvaise qualité","Câblage chauffage défaillant"]',
 '["Vérifier le chauffage du capteur A/F.","Remplacer le capteur A/F (durée de vie 100 000 km).","Utiliser du carburant de qualité supérieure."]'),
("P1150","TOYOTA","medium","A/F sensor circuit range bank 2","Capteur A/F — hors plage B2",
 '["Capteur A/F B2 HS","Fuite échappement B2","Câblage endommagé côté B2"]',
 '["Inspecter le collecteur côté B2.","Tester le capteur A/F B2.","Remplacer si HS."]'),
("P1200","TOYOTA","high","Fuel pump relay circuit","Circuit relais pompe carburant — défaut",
 '["Relais pompe carburant HS","Câblage endommagé","ECM défaillant"]',
 '["Vérifier le relais pompe (circuit de commande ECM).","Tester la tension pompe (+12V).","Contrôler l\'ECM."]'),
("P1300","TOYOTA","high","Igniter circuit bank 1","Circuit allumeur — B1",
 '["Module allumage HS","Câblage allumeur endommagé","Bobines défectueuses"]',
 '["Tester chaque bobine d\'allumage.","Vérifier les câbles haute tension.","Remplacer l\'allumeur si nécessaire."]'),
("P1310","TOYOTA","high","Igniter circuit bank 2","Circuit allumeur — B2",
 '["Module allumage B2 HS","Câblage allumeur B2","Bobines B2 défectueuses"]',
 '["Tester les bobines côté B2.","Vérifier le câblage.","Remplacer l\'allumeur B2."]'),
("P1349","TOYOTA","medium","VVT system malfunction bank 1","Système VVT — défaut B1",
 '["Huile moteur sale ou niveau bas","Actuateur VVT colmaté","Capteur VVT HS"]',
 '["Changer l\'huile moteur (0W20 Toyota recommandé).","Nettoyer l\'actuateur VVT.","Remplacer le capteur arbre à cames."]'),
("P1400","TOYOTA","medium","Sub-throttle valve actuator","Actuateur papillon secondaire — défaut",
 '["Actuateur papillon secondaire HS","Corps papillon encrassé","Câblage endommagé"]',
 '["Nettoyer le corps papillon.","Initialiser le papillon (clé on/off).","Remplacer si motorisation HS."]'),
("P1420","TOYOTA","medium","Short fuel trim additive air lean B1","Correction court terme — pauvre B1",
 '["Fuite d\'air post-MAF","Injecteurs partiellement bouchés","Capteur MAF encrassé"]',
 '["Inspecter les durites d\'admission.","Nettoyer les injecteurs.","Nettoyer ou remplacer le MAF."]'),
("P1500","TOYOTA","medium","Starter signal circuit","Circuit signal démarreur — défaut",
 '["Commutateur d\'allumage HS","Câblage signal STA endommagé","ECM défaillant"]',
 '["Vérifier le signal STA au démarrage (12V).","Contrôler le commutateur clé.","Diagnostiquer l\'ECM."]'),
("P1600","TOYOTA","high","ECU BATT terminal circuit","Alimentation permanente ECU — circuit",
 '["Fusible permanent ECU claqué","Câblage +B endommagé","Contacteur à commande vocale HS"]',
 '["Vérifier le fusible EFI MAIN.","Contrôler le câblage +B ECU.","Tester la tension permanente sur ECU."]'),
("P1633","TOYOTA","high","ECM internal fault","ECM — défaut interne",
 '["Surtension ayant endommagé l\'ECM","ECM endommagé par humidité","Virus de reprogrammation"]',
 '["Vérifier la tension batterie (pas de surtension).","Contrôler l\'étanchéité du boîtier ECM.","Remplacer l\'ECM si interne."]'),
("P1780","TOYOTA","medium","Park-neutral switch signal","Signal commutateur P/N — défaut",
 '["Commutateur P/N HS ou désréglé","Câblage endommagé","ECT défaillant"]',
 '["Vérifier la position du sélecteur.","Régler le commutateur P/N.","Remplacer si signal incorrect."]'),

# ═══════════════════════════════════════════════════════════════════════════
# HONDA / ACURA — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1106","HONDA","medium","Barometric pressure sensor range","Capteur pression atmosphérique — hors plage",
 '["Capteur MAP/BARO HS","Durite dépression percée","ECM défaillant"]',
 '["Inspecter les durites de dépression.","Tester le capteur MAP (0,5-4,5V).","Remplacer si hors plage."]'),
("P1107","HONDA","medium","Barometric pressure sensor low input","Capteur pression atmosphérique — signal faible",
 '["Court-circuit masse","Capteur HS","Alimentation 5V absente"]',
 '["Vérifier l\'alimentation 5V du capteur.","Tester le signal capteur.","Remplacer le capteur MAP."]'),
("P1121","HONDA","medium","Throttle position lower than expected","Position papillon inférieure à la normale",
 '["Corps papillon encrassé","Câble d\'accélérateur détendu","Capteur TPS HS"]',
 '["Nettoyer le corps papillon.","Régler ou remplacer le câble d\'accélérateur.","Étalonner le TPS."]'),
("P1128","HONDA","medium","MAP sensor signal lower than expected","Capteur MAP — signal inférieur à la normale",
 '["Fuite admission après MAP","Débitmètre HS","Calculateur défaillant"]',
 '["Vérifier étanchéité admission.","Tester le capteur MAP.","Contrôler la dépression au ralenti."]'),
("P1129","HONDA","medium","MAP sensor signal higher than expected","Capteur MAP — signal supérieur à la normale",
 '["Court-circuit 5V","Capteur MAP HS","Calculateur défaillant"]',
 '["Vérifier câblage capteur.","Tester le capteur MAP.","Remplacer si nécessaire."]'),
("P1162","HONDA","medium","A/F sensor circuit bank 1","Capteur A/F — circuit B1",
 '["Capteur A/F HS","Câblage endommagé","Fuite collecteur d\'échappement"]',
 '["Inspecter le collecteur.","Vérifier câblage capteur A/F.","Remplacer le capteur."]'),
("P1163","HONDA","medium","A/F sensor slow response bank 1","Capteur A/F — réponse lente B1",
 '["Capteur A/F vieilli","Chauffage défaillant","Carburant contaminé"]',
 '["Tester le chauffage (10-40Ω).","Remplacer le capteur A/F.","Utiliser du carburant propre."]'),
("P1167","HONDA","medium","A/F sensor heater circuit bank 1","Chauffage capteur A/F — circuit B1",
 '["Circuit chauffage coupé","Fusible chauffage claqué","ECM défaillant"]',
 '["Vérifier le fusible du chauffage O2/A/F.","Tester la résistance chauffage (10-40Ω).","Contrôler l\'ECM."]'),
("P1243","HONDA","high","Second secondary O2 sensor slow response","Sonde O2 secondaire — réponse lente",
 '["Sonde O2 aval vieille","Catalyseur dégradé","Câblage sonde endommagé"]',
 '["Vérifier l\'état du catalyseur.","Tester la sonde O2 aval.","Remplacer la sonde si HS."]'),
("P1259","HONDA","high","VTEC system malfunction","Système VTEC — défaut",
 '["Huile moteur sale ou niveau bas","Electrovanne VTEC HS","Pression huile insuffisante"]',
 '["Changer l\'huile moteur (Honda 5W30).","Tester l\'électrovanne VTEC (14-30Ω).","Vérifier la pression huile (>0,5 bar)."]'),
("P1297","HONDA","medium","ELD circuit low input","Circuit ELD — signal faible",
 '["Capteur ELD HS","Câblage endommagé","Alternateur défaillant"]',
 '["Vérifier la charge électrique.","Tester l\'alternateur.","Remplacer le capteur ELD si HS."]'),
("P1298","HONDA","medium","ELD circuit high input","Circuit ELD — signal élevé",
 '["Surintensité électrique","Capteur ELD HS","Court-circuit"]',
 '["Vérifier les consommateurs électriques.","Tester le capteur ELD.","Contrôler l\'alternateur."]'),
("P1316","HONDA","high","Spark plug voltage detection bank 1","Détection tension bougie — B1",
 '["Bougies usées","Bobines HS","Câbles haute tension défaillants"]',
 '["Remplacer les bougies (Honda recommande 30 000 km).","Tester chaque bobine.","Vérifier les câbles HT."]'),
("P1324","HONDA","high","Knock sensor system bank 1","Système capteur cliquetis — B1",
 '["Capteur cliquetis HS","Câblage desserré","Carburant octane insuffisant"]',
 '["Utiliser du carburant SP95/SP98.","Tester la résistance capteur (∞Ω).","Remplacer le capteur cliquetis."]'),
("P1399","HONDA","high","Random misfire detected","Ratés d\'allumage aléatoires — défaut générique",
 '["Bougies usées","Bobines défectueuses","Injecteurs encrassés","Distribution usée"]',
 '["Remplacer bougies et câbles HT.","Tester chaque bobine.","Nettoyer les injecteurs.","Vérifier la distribution."]'),
("P1456","HONDA","medium","EVAP small leak fuel tank","EVAP — petite fuite côté réservoir",
 '["Bouchon réservoir endommagé","Joint bouchon usé","Durite évent fendue"]',
 '["Remplacer le bouchon réservoir Honda.","Inspecter les durits d\'évent.","Vérifier le charbon actif."]'),
("P1457","HONDA","medium","EVAP small leak canister side","EVAP — petite fuite côté canister",
 '["Electrovanne purge HS","Durite canister fissurée","Joint canister défaillant"]',
 '["Tester l\'électrovanne purge.","Inspecter les durites canister.","Remplacer le canister si endommagé."]'),
("P1491","HONDA","medium","EGR valve lift insufficient","Levée vanne EGR — insuffisante",
 '["Vanne EGR encrassée au carbone","Actionneur EGR HS","Capteur levée HS"]',
 '["Nettoyer la vanne EGR.","Tester l\'actionneur.","Remplacer la vanne si encrassée."]'),
("P1498","HONDA","medium","EGR valve lift excessive","Levée vanne EGR — excessive",
 '["Vanne EGR coincée ouverte","Ressort de rappel cassé"]',
 '["Inspecter la vanne EGR.","Remplacer la vanne si coincée."]'),

# ═══════════════════════════════════════════════════════════════════════════
# BMW / MINI — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1083","BMW","medium","Mixture control lean bank 1 sensor 1","Régulation mélange pauvre — B1 S1",
 '["Fuite d\'air admission","Débitmètre encrassé","Injecteurs bouché côté B1"]',
 '["Inspecter les durites admission.","Nettoyer le débitmètre.","Tester les injecteurs B1."]'),
("P1084","BMW","medium","Mixture control rich bank 1 sensor 1","Régulation mélange riche — B1 S1",
 '["Injecteurs qui fuient B1","Capteur MAF défectueux","Régulateur de pression HS"]',
 '["Vérifier les injecteurs B1 (pas de goutte).","Nettoyer ou remplacer le débitmètre.","Contrôler le régulateur de pression."]'),
("P1085","BMW","medium","Mixture control lean bank 2","Régulation mélange pauvre — B2",
 '["Fuite d\'air côté B2","Capteur MAF HS","Injecteurs B2 bouché"]',
 '["Inspecter admission côté B2.","Tester les injecteurs.","Remplacer le MAF si HS."]'),
("P1128","BMW","medium","Long fuel trim rich bank 1","Apprentissage carburant trop riche — B1",
 '["Débitmètre surestimant l\'air","Fuite d\'huile aspirée","Régulateur de pression HS"]',
 '["Nettoyer le débitmètre.","Vérifier joints spi et joint de culasse.","Tester régulateur pression carburant."]'),
("P1188","BMW","high","Mixture adaptation rich stop bank 1","Adaptation richesse à la butée riche — B1",
 '["Dérivé débitmètre","Sonde lambda amont défaillante","Fuite injection"]',
 '["Remplacer le débitmètre (MAF).","Tester la sonde lambda amont.","Vérifier les injecteurs."]'),
("P1189","BMW","high","Mixture adaptation lean stop bank 2","Adaptation richesse à la butée pauvre — B2",
 '["Fuite d\'air côté B2","Injecteurs B2 usés","Pression carburant insuffisante"]',
 '["Inspecter l\'admission B2.","Tester les injecteurs B2.","Mesurer pression carburant."]'),
("P1343","BMW","high","Misfire cylinder 1 with fuel cut","Raté allumage cylindre 1 — coupure injection",
 '["Bobine C1 HS","Bougie C1 usée","Injecteur C1 défaillant"]',
 '["Permuter la bobine C1 et tester.","Remplacer la bougie C1.","Tester l\'injecteur C1."]'),
("P1344","BMW","high","Misfire cylinder 2 with fuel cut","Raté allumage cylindre 2 — coupure injection",
 '["Bobine C2 HS","Bougie C2 usée","Injecteur C2 défaillant"]',
 '["Permuter bobine C2.","Remplacer bougie C2.","Tester injecteur C2."]'),
("P1345","BMW","high","Misfire cylinder 3 with fuel cut","Raté allumage cylindre 3 — coupure injection",
 '["Bobine C3 HS","Bougie C3 usée","Compression faible C3"]',
 '["Permuter bobine C3.","Remplacer bougie C3.","Mesurer la compression C3."]'),
("P1346","BMW","high","Misfire cylinder 4 with fuel cut","Raté allumage cylindre 4 — coupure injection",
 '["Bobine C4 HS","Bougie C4 usée","Joint de culasse endommagé"]',
 '["Permuter bobine C4.","Remplacer bougie C4.","Vérifier joint de culasse."]'),
("P1397","BMW","medium","Camshaft position sensor B bank 1","Capteur position arbre à cames B — B1",
 '["Capteur arbre à cames HS","Roue phonique endommagée","Câblage coupé"]',
 '["Vérifier l\'entrefer capteur.","Tester la résistance capteur.","Remplacer si HS."]'),
("P1420","BMW","medium","Secondary air injection system bank 1","Injection d\'air secondaire — B1",
 '["Pompe d\'air secondaire HS","Clapet antiretour bloqué","Electrovanne HS"]',
 '["Tester la pompe d\'air (12V direct).","Vérifier le clapet antiretour.","Tester l\'électrovanne."]'),
("P1447","BMW","medium","EVAP canister purge valve circuit","Electrovanne purge canister — circuit",
 '["Electrovanne purge HS","Câblage coupé","ECU défaillant"]',
 '["Tester l\'électrovanne purge (26-36Ω).","Vérifier le câblage.","Contrôler le signal PWM."]'),
("P1500","BMW","medium","Idle speed control valve circuit","Valve de régulation ralenti — circuit",
 '["Valve ralenti encrassée","Câblage endommagé","Calculateur MSS/DME HS"]',
 '["Nettoyer la valve de ralenti (IPA).","Vérifier le câblage.","Tester la résistance (10-15Ω)."]'),
("P1519","BMW","high","Throttle body DISA — intake malfunction","Corps papillon DISA — défaut admission",
 '["Volet DISA cassé","Came DISA en plastique brisée","Câblage DISA"]',
 '["Inspecter le volet DISA (très fragile sur M54).","Remplacer l\'actionneur DISA.","Vérifier câblage."]'),
("P1624","BMW","high","Engine start immobiliser fault","Antidémarrage — défaut démarrage",
 '["Clé EWS non reconnue","EWS (antidémarrage) HS","Câblage EWS/DME"]',
 '["Tester une clé de secours.","Vérifier la communication EWS.","Synchroniser EWS et DME."]'),

# ═══════════════════════════════════════════════════════════════════════════
# OPEL / VAUXHALL — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","OPEL","medium","MAF sensor circuit intermittent","Débitmètre — circuit intermittent",
 '["Débitmètre encrassé","Connecteur lâche","Filtre à air saturé"]',
 '["Nettoyer le débitmètre.","Vérifier le connecteur.","Remplacer le filtre à air."]'),
("P1114","OPEL","medium","ECT sensor circuit low bank 1","Capteur température eau — signal faible B1",
 '["Capteur ECT HS","Câblage coupé vers capteur","Court-circuit masse"]',
 '["Vérifier la résistance capteur (à 20°C = 2400Ω).","Contrôler le câblage.","Remplacer le capteur."]'),
("P1115","OPEL","medium","ECT sensor circuit high bank 1","Capteur température eau — signal élevé B1",
 '["Capteur ECT HS","Circuit ouvert","Câblage endommagé"]',
 '["Vérifier le connecteur.","Tester la résistance capteur.","Remplacer si nécessaire."]'),
("P1120","OPEL","medium","Throttle position sensor 1 circuit low","Capteur position papillon 1 — signal faible",
 '["Capteur TPS HS","Câblage endommagé","ECU Simtec défaillant"]',
 '["Vérifier signal TPS (0,5V à vide).","Contrôler le câblage.","Remplacer le TPS."]'),
("P1125","OPEL","high","Pedal position sensor A performance","Capteur pédale accélérateur A — performance",
 '["Pédalier ETC défaillant","Câblage endommagé","ECU défaillant"]',
 '["Vérifier les deux signaux pédalier.","Contrôler le câblage.","Remplacer le pédalier."]'),
("P1171","OPEL","high","Fuel system lean bank 1","Mélange trop pauvre — B1",
 '["Injecteurs bouché","Pression carburant faible","Fuite d\'air admission"]',
 '["Mesurer pression carburant.","Nettoyer les injecteurs.","Inspecter l\'admission."]'),
("P1248","OPEL","high","Injection quantity adjustment fault","Ajustement quantité injection — défaut",
 '["Pompe haute pression CDTi HS","Injecteurs usés","Câblage pompe endommagé"]',
 '["Mesurer la pression rail CDTi.","Tester les fuites retour injecteurs.","Diagnostiquer la pompe HP."]'),
("P1280","OPEL","high","Fuel injection quantity signal low","Signal quantité injection — trop faible",
 '["Pompe carburant faible","Filtre carburant colmaté","Pression rail insuffisante"]',
 '["Remplacer le filtre carburant.","Mesurer la pression rail.","Tester la pompe carburant."]'),
("P1380","OPEL","medium","EGR valve circuit A open","Circuit vanne EGR A — circuit ouvert",
 '["Câblage EGR interrompu","Electrovanne EGR HS","Calculateur défaillant"]',
 '["Vérifier câblage EGR.","Tester résistance électrovanne (10-30Ω).","Contrôler l\'alimentation."]'),
("P1400","OPEL","medium","EGR system flow detected","Débit EGR — flux détecté hors commande",
 '["Vanne EGR coincée ouverte","Fuite joint EGR","Calculateur défaillant"]',
 '["Inspecter la vanne EGR.","Vérifier étanchéité.","Remplacer la vanne si coincée."]'),
("P1545","OPEL","high","Throttle valve actuator circuit","Circuit actionneur papillon — défaut",
 '["Actionneur papillon HS","Corps papillon encrassé","Câblage moteur papillon"]',
 '["Nettoyer le corps papillon.","Initialiser le papillon.","Remplacer le corps papillon si HS."]'),
("P1600","OPEL","high","PCM battery voltage low","Tension batterie PCM — faible",
 '["Batterie faible","Alternateur HS","Mauvaise masse"]',
 '["Tester la batterie.","Vérifier l\'alternateur.","Contrôler les masses."]'),

# ═══════════════════════════════════════════════════════════════════════════
# FIAT / ALFA ROMEO / LANCIA — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","FIAT","medium","MAF sensor intermittent","Débitmètre — signal intermittent",
 '["Débitmètre Bosch encrassé","Filtre à air colmaté","Connecteur lâche"]',
 '["Nettoyer le débitmètre à l\'IPA.","Remplacer le filtre à air.","Vérifier le connecteur."]'),
("P1110","FIAT","medium","Intake air temperature sensor low","Capteur température air admission — signal faible",
 '["Capteur IAT intégré au MAF HS","Câblage endommagé"]',
 '["Vérifier la résistance capteur IAT.","Remplacer le MAF si IAT intégré."]'),
("P1170","FIAT","medium","O2 sensor heater circuit bank 1","Chauffage sonde lambda — circuit B1",
 '["Circuit chauffage coupé","Fusible chauffage claqué","ECU HS"]',
 '["Vérifier le fusible sonde O2.","Tester la résistance chauffage (3-15Ω).","Contrôler l\'ECU."]'),
("P1172","FIAT","high","Fuel system rich bank 1","Mélange trop riche — B1",
 '["Injecteurs qui fuient","Pression carburant excessive","MAF surestimant l\'air"]',
 '["Tester les injecteurs (pas de goutte).","Mesurer la pression carburant.","Nettoyer le MAF."]'),
("P1173","FIAT","high","Fuel system lean bank 1","Mélange trop pauvre — B1",
 '["Fuite d\'air après MAF","Pompe carburant faible","Injecteurs bouché"]',
 '["Inspecter les durites admission.","Mesurer la pression carburant.","Nettoyer les injecteurs."]'),
("P1250","FIAT","high","Fuel pressure regulator solenoid fault","Solénoïde régulateur pression carburant — défaut",
 '["Régulateur de pression HS","Câblage solénoïde endommagé","ECU HS"]',
 '["Mesurer la pression carburant.","Tester le solénoïde.","Remplacer le régulateur si HS."]'),
("P1300","FIAT","high","Boost control pressure too low","Pression turbo — trop faible",
 '["Wastegate coincée ouverte","Durite de suralimentation trouée","Capteur pression turbo HS"]',
 '["Vérifier les durites turbo.","Tester la wastegate.","Contrôler le capteur MAP turbo."]'),
("P1301","FIAT","high","Boost control pressure too high","Pression turbo — trop élevée",
 '["Wastegate coincée fermée","Valve de décharge HS","Capteur pression turbo HS"]',
 '["Vérifier la wastegate.","Tester la valve de décharge.","Inspecter le circuit suralimentation."]'),
("P1337","FIAT","high","Crankshaft sensor signal missing","Signal capteur vilebrequin absent",
 '["Capteur PMH HS","Roue phonique endommagée","Câblage coupé"]',
 '["Vérifier l\'entrefer (0,8-1,5mm).","Tester la résistance (220-900Ω).","Inspecter la roue phonique."]'),
("P1351","FIAT","high","Ignition coil control circuit fault","Circuit commande bobine allumage — défaut",
 '["Bobine HS","Module allumage défaillant","Câblage haute tension"]',
 '["Permuter les bobines.","Mesurer la résistance primaire.","Remplacer la bobine défectueuse."]'),
("P1400","FIAT","medium","EGR valve control open circuit","Circuit commande EGR — circuit ouvert",
 '["Câblage EGR coupé","Electrovanne EGR HS","ECU défaillant"]',
 '["Vérifier le câblage EGR.","Tester l\'électrovanne.","Contrôler l\'ECU."]'),
("P1403","FIAT","medium","EGR valve differential pressure fault","Pression différentielle EGR — défaut",
 '["Capteur pression différentielle HS","Durites capteur bouchées","Vanne EGR encrassée"]',
 '["Nettoyer les durites capteur.","Tester le capteur différentiel.","Nettoyer la vanne EGR."]'),
("P1480","FIAT","medium","Cooling fan relay 1 circuit","Circuit relais ventilateur 1 — défaut",
 '["Relais ventilateur HS","Câblage endommagé","ECU défaillant"]',
 '["Tester le relais ventilateur.","Vérifier l\'alimentation ventilateur.","Contrôler l\'ECU."]'),
("P1516","FIAT","high","Throttle body actuator fault","Actionneur corps papillon — défaut",
 '["Corps papillon électronique HS","Capteur TPS interne HS","Câblage actionneur"]',
 '["Réinitialiser le papillon.","Nettoyer le corps papillon.","Remplacer si motorisation HS."]'),
("P1600","FIAT","high","ECU supply voltage low","Tension alimentation ECU — faible",
 '["Batterie faible","Mauvaise masse","Alternateur défaillant"]',
 '["Tester la batterie (>12,4V).","Vérifier les masses.","Tester l\'alternateur."]'),
("P1614","FIAT","high","Immobiliser fault","Antidémarrage — défaut",
 '["Transpondeur clé HS","ECU non appris","Antenne immobiliser défaillante"]',
 '["Tester avec clé de secours.","Vérifier l\'antenne immobiliser.","Reprogrammer via outil Fiat."]'),

# ═══════════════════════════════════════════════════════════════════════════
# VOLVO — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1020","VOLVO","medium","Valve timing solenoid A fault","Solénoïde calage distribution A — défaut",
 '["Solénoïde VVT encrassé","Câblage solénoïde endommagé","Huile moteur dégradée"]',
 '["Changer l\'huile moteur.","Nettoyer le solénoïde VVT.","Vérifier le câblage."]'),
("P1021","VOLVO","medium","Valve timing solenoid B fault","Solénoïde calage distribution B — défaut",
 '["Solénoïde VVT B HS","Pression huile insuffisante","Calculateur ECM HS"]',
 '["Vérifier la pression huile.","Tester le solénoïde.","Remplacer si HS."]'),
("P1080","VOLVO","medium","Fuel trim rich bank 1 at part load","Correction riche à charge partielle — B1",
 '["MAF déréglé","Injecteurs qui fuient","Régulateur pression HS"]',
 '["Nettoyer le MAF.","Tester les injecteurs.","Mesurer la pression carburant."]'),
("P1114","VOLVO","medium","ECT sensor circuit low","Capteur eau — circuit faible",
 '["Capteur ECT HS ou court-circuit","Câblage endommagé"]',
 '["Vérifier la résistance capteur.","Contrôler le câblage.","Remplacer si HS."]'),
("P1171","VOLVO","high","Fuel system too lean bank 1","Mélange trop pauvre — B1",
 '["Fuite d\'air admission","MAF encrassé","Injecteurs bouché"]',
 '["Inspecter l\'admission.","Nettoyer le MAF.","Tester les injecteurs."]'),
("P1181","VOLVO","high","Fuel system too lean bank 2","Mélange trop pauvre — B2",
 '["Fuite côté B2","Capteur MAF HS","Injecteurs B2 HS"]',
 '["Inspecter admission B2.","Remplacer le MAF.","Tester injecteurs B2."]'),
("P1238","VOLVO","high","Throttle module communication fault","Communication module papillon — défaut",
 '["Bus CAN papillon interrompu","ETM (Electronic Throttle Module) HS","Câblage CAN défaillant"]',
 '["Vérifier le bus CAN (résistance 120Ω).","Tester le module ETM.","Remplacer l\'ETM si nécessaire."]'),
("P1300","VOLVO","high","Misfire — catalyst damaging","Ratés d\'allumage — risque catalyseur",
 '["Bougies usées","Bobines défectueuses","Injecteurs HS"]',
 '["Remplacer les bougies.","Permuter et tester les bobines.","Nettoyer les injecteurs."]'),
("P1390","VOLVO","medium","Knock sensor bank 1 circuit","Circuit capteur cliquetis — B1",
 '["Capteur cliquetis HS","Câblage dessous le moteur endommagé","Calculateur HS"]',
 '["Vérifier le câblage capteur.","Tester la résistance (∞Ω).","Remplacer si HS."]'),
("P1400","VOLVO","medium","EGR valve circuit","Circuit vanne EGR — défaut",
 '["Vanne EGR encrassée","Câblage endommagé","ECM défaillant"]',
 '["Nettoyer la vanne EGR.","Vérifier le câblage.","Tester l\'actionneur."]'),
("P1440","VOLVO","medium","EVAP large leak detected","EVAP — grande fuite détectée",
 '["Durite EVAP déconnectée","Canister endommagé","Electrovanne purge HS"]',
 '["Inspecter toutes les durites EVAP.","Tester l\'électrovanne purge.","Remplacer le canister si fissuré."]'),
("P1602","VOLVO","high","Powertrain control module KAM reset","ECM — mémoire effacée (batterie déconnectée)",
 '["Batterie déconnectée","Fusible ECM claqué","Intervention calculateur"]',
 '["Effectuer un cycle de conduite complet.","Vérifier que tous les systèmes fonctionnent.","Aucune action si récente déconnexion batterie."]'),
("P1616","VOLVO","high","Immobiliser — wrong code","Antidémarrage — code erroné",
 '["Clé non programmée pour ce véhicule","ECM/IMMO non synchronisé","Batterie trop faible lors démarrage"]',
 '["Recharger la batterie.","Utiliser la clé originale.","Reprogrammer via outil VIDA."]'),

# ═══════════════════════════════════════════════════════════════════════════
# KIA / HYUNDAI — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","KIA","medium","MAF sensor fault","Débitmètre — défaut",
 '["Débitmètre encrassé","Câblage endommagé","Filtre à air colmaté"]',
 '["Nettoyer le débitmètre.","Vérifier le connecteur.","Remplacer le filtre à air."]'),
("P1105","KIA","medium","MAP/BARO sensor switching solenoid","Solénoïde commutation MAP/BARO — défaut",
 '["Solénoïde HS","Câblage endommagé","ECM défaillant"]',
 '["Vérifier le solénoïde.","Contrôler le câblage.","Diagnostiquer l\'ECM."]'),
("P1115","KIA","medium","ECT sensor circuit intermittent","Capteur température eau — circuit intermittent",
 '["Connecteur capteur ECT lâche","Câblage dégradé par chaleur","Capteur HS"]',
 '["Inspecter le connecteur ECT.","Vérifier le câblage.","Remplacer le capteur si HS."]'),
("P1120","KIA","medium","Throttle position sensor low","Capteur position papillon — signal faible",
 '["Capteur TPS HS","Corps papillon encrassé","Câblage TPS endommagé"]',
 '["Nettoyer le corps papillon.","Tester le signal TPS.","Remplacer le TPS."]'),
("P1130","KIA","medium","O2 sensor heater bank 1 sensor 1","Chauffage sonde O2 — B1 S1",
 '["Circuit chauffage coupé","Fusible O2 HS","ECM défaillant"]',
 '["Vérifier le fusible.","Tester la résistance chauffage.","Contrôler l\'ECM."]'),
("P1166","KIA","medium","A/F sensor heater relay circuit","Circuit relais chauffage capteur A/F — défaut",
 '["Relais chauffage HS","Câblage relais endommagé","ECM défaillant"]',
 '["Tester le relais chauffage.","Vérifier le câblage.","Contrôler l\'ECM."]'),
("P1192","KIA","medium","Inlet air temp sensor circuit low","Capteur température air admission — signal faible",
 '["Capteur IAT HS","Câblage endommagé","Court-circuit masse"]',
 '["Vérifier la résistance capteur IAT.","Contrôler le câblage.","Remplacer le capteur."]'),
("P1250","KIA","high","Fuel pressure regulator valve fault","Vanne régulateur pression carburant — défaut",
 '["Vanne régulateur HS","Câblage endommagé","ECM défaillant"]',
 '["Mesurer la pression carburant.","Tester la vanne régulateur.","Contrôler l\'ECM."]'),
("P1307","KIA","high","Chassis acceleration sensor signal","Signal capteur accélération châssis — défaut",
 '["Capteur accélération HS","Câblage endommagé","Module ESP défaillant"]',
 '["Vérifier le capteur accélération.","Inspecter le câblage.","Diagnostiquer le module ESP."]'),
("P1345","KIA","high","Crankshaft/camshaft timing","Calage vilebrequin/arbre à cames",
 '["Courroie distribution sautée","Capteur PMH ou arbre à cames HS","Chaîne allongée"]',
 '["Vérifier le calage distribution.","Inspecter les capteurs PMH.","Contrôler la chaîne ou courroie."]'),
("P1400","KIA","medium","EGR valve circuit fault","Circuit vanne EGR — défaut",
 '["Vanne EGR encrassée","Câblage endommagé","ECM défaillant"]',
 '["Nettoyer la vanne EGR.","Vérifier le câblage.","Contrôler l\'ECM."]'),
("P1449","KIA","medium","Canister close valve solenoid fault","Solénoïde valve fermeture canister — défaut",
 '["Solénoïde HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde.","Vérifier le câblage.","Remplacer si HS."]'),
("P1500","KIA","medium","Vehicle speed sensor 1 fault","Capteur vitesse 1 — défaut",
 '["Capteur VSS HS","Câblage endommagé","ECM défaillant"]',
 '["Vérifier le capteur VSS.","Contrôler le câblage.","Diagnostiquer l\'ECM."]'),
("P1529","KIA","medium","IMRC solenoid fault","Solénoïde IMRC — défaut",
 '["Solénoïde IMRC HS","Câblage endommagé","Corps admision défaillant"]',
 '["Tester le solénoïde IMRC.","Vérifier le câblage.","Inspecter les volets admission."]'),
("P1614","KIA","high","Immobiliser code mismatch","Antidémarrage — code non concordant",
 '["Clé non programmée","IMMO défaillant","ECM incompatible"]',
 '["Tester avec clé originale.","Reprogrammer les clés.","Intervention KIA si nécessaire."]'),
("P1693","KIA","medium","Transmission control indicator lamp fault","Voyant contrôle boîte — défaut",
 '["Câblage voyant TCU HS","TCU défaillant","Calculateur instrument HS"]',
 '["Vérifier le câblage voyant TCU.","Diagnostiquer le TCU.","Contrôler l\'instrument cluster."]'),

# ═══════════════════════════════════════════════════════════════════════════
# SKODA — codes spécifiques (partage beaucoup avec VW)
# ═══════════════════════════════════════════════════════════════════════════
("P0299","SKODA","high","Turbocharger underboost","Pression turbo insuffisante",
 '["Durite d\'intercooler fendue","Vanne N75 HS","Turbocompresseur usé","Actuateur wastegate défaillant"]',
 '["Inspecter toutes les durites de suralimentation.","Tester la vanne N75 (25-35Ω).","Vérifier l\'actionneur wastegate.","Envisager une révision turbo."]'),
("P0411","SKODA","medium","Secondary air injection incorrect flow","Débit injection air secondaire incorrect",
 '["Pompe d\'air secondaire HS","Clapet antiretour bloqué","Electrovanne N112 HS"]',
 '["Tester la pompe d\'air secondaire.","Vérifier le clapet antiretour.","Tester l\'électrovanne N112."]'),
("P0507","SKODA","medium","Idle air control high","Ralenti élevé",
 '["Corps papillon encrassé","Fuite d\'air admission","Capteur papillon HS"]',
 '["Nettoyer le corps papillon (06A903023).","Inspecter les durites.","Effectuer une adaptation papillon."]'),
("P1136","SKODA","medium","Long fuel trim bank 1 lean","Apprentissage carburant pauvre — B1",
 '["Débitmètre encrassé","Fuite d\'air","Injecteurs bouché"]',
 '["Nettoyer le débitmètre.","Inspecter les durites.","Tester les injecteurs."]'),
("P1176","SKODA","medium","O2 sensor correction B1 limit rich","Correction O2 à la limite riche — B1",
 '["Sonde O2 HS","Injecteurs qui fuient","MAF défaillant"]',
 '["Remplacer la sonde O2 si >100 000km.","Tester les injecteurs.","Vérifier le MAF."]'),
("P1177","SKODA","medium","O2 sensor correction B2 limit lean","Correction O2 à la limite pauvre — B2",
 '["Fuite d\'air côté B2","Sonde O2 B2 HS","Injecteurs B2 bouché"]',
 '["Inspecter l\'admission B2.","Tester la sonde O2.","Vérifier les injecteurs."]'),
("P1250","SKODA","high","Fuel pressure regulation valve N276","Vanne régulation pression N276 — défaut",
 '["Vanne N276 encrassée","Câblage N276 endommagé","Calculateur Simos/Bosch HS"]',
 '["Mesurer la pression rail.","Tester la vanne N276 (commande PWM).","Nettoyer ou remplacer la vanne."]'),
("P1340","SKODA","high","Misfire — camshaft/crankshaft position","Calage arbre à cames/vilebrequin",
 '["Chaîne distribution allongée","Capteur arbre à cames HS","Capteur PMH HS"]',
 '["Vérifier le calage distribution.","Tester les capteurs.","Remplacement chaîne si allongée."]'),
("P1580","SKODA","high","Throttle actuator B1 motor circuit","Moteur actionneur papillon — circuit B1",
 '["Motorisation papillon HS","Corps papillon encrassé","Câblage moteur papillon"]',
 '["Nettoyer le corps papillon.","Effectuer l\'adaptation.","Remplacer le corps papillon si HS."]'),
("P1612","SKODA","high","Immobiliser — ECM not programmed","Antidémarrage — ECM non programmé",
 '["ECM remplacé sans adaptation","Clé de sécurité non concordante","IMMO HS"]',
 '["Adapter l\'ECM avec VCDS.","Synchroniser l\'immobiliser.","Intervention VAG nécessaire."]'),
("P1624","SKODA","high","Immobiliser — incorrect code","Antidémarrage — code incorrect",
 '["Clé transponder HS","IMMO non synchronisé","Batterie trop faible"]',
 '["Recharger la batterie.","Tester une autre clé.","Adapter via VCDS."]'),

# ═══════════════════════════════════════════════════════════════════════════
# MITSUBISHI — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","MITSUBISHI","medium","Induction control motor position sensor","Capteur position moteur admission — défaut",
 '["Capteur MIVEC HS","Câblage endommagé","Calculateur ECM HS"]',
 '["Vérifier le signal capteur.","Contrôler le câblage.","Diagnostiquer l\'ECM."]'),
("P1103","MITSUBISHI","high","Turbocharger wastegate actuator","Actionneur wastegate turbo — défaut",
 '["Actionneur wastegate HS","Tige d\'actionneur déconnectée","Durite commande percée"]',
 '["Vérifier la tige d\'actionneur.","Inspecter la durite de commande.","Tester l\'actionneur."]'),
("P1300","MITSUBISHI","high","Igniter circuit 1","Circuit allumeur 1 — défaut",
 '["Module allumage HS","Bobine 1 défectueuse","Câblage allumage endommagé"]',
 '["Tester la bobine 1.","Vérifier le câblage.","Remplacer le module allumage."]'),
("P1301","MITSUBISHI","high","Igniter circuit 2","Circuit allumeur 2 — défaut",
 '["Module allumage 2 HS","Bobine 2 défectueuse","Câblage endommagé"]',
 '["Tester la bobine 2.","Vérifier le câblage.","Remplacer si nécessaire."]'),
("P1310","MITSUBISHI","high","Igniter circuit 3","Circuit allumeur 3 — défaut",
 '["Module allumage 3 HS","Bobine 3 défectueuse","Câblage endommagé"]',
 '["Tester la bobine 3.","Vérifier le câblage.","Remplacer si nécessaire."]'),
("P1400","MITSUBISHI","medium","EGR solenoid circuit fault","Circuit solénoïde EGR — défaut",
 '["Solénoïde EGR HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde EGR.","Vérifier le câblage.","Contrôler l\'ECM."]'),
("P1500","MITSUBISHI","medium","Alternator FR signal circuit","Signal FR alternateur — circuit",
 '["Alternateur HS ou câblage","ECM défaillant","Problème de charge batterie"]',
 '["Vérifier la tension de charge alternateur.","Tester le signal FR.","Remplacer l\'alternateur si HS."]'),
("P1600","MITSUBISHI","high","ECU power fault","Alimentation ECU — défaut",
 '["Fusible ECU claqué","Câblage alimentation coupé","Relais principal HS"]',
 '["Vérifier le fusible ECU.","Tester le relais principal.","Contrôler l\'alimentation."]'),
("P1715","MITSUBISHI","medium","Pulse generator A circuit (input shaft)","Capteur vitesse A arbre entrée boîte — circuit",
 '["Capteur vitesse boîte HS","Câblage endommagé","Calculateur TCU HS"]',
 '["Vérifier le capteur vitesse entrée.","Contrôler le câblage.","Diagnostiquer le TCU."]'),
("P1750","MITSUBISHI","high","Solenoid valve assembly fault","Ensemble électrovannes boîte — défaut",
 '["Electrovannes BVA HS","Huile boîte dégradée","Calculateur TCU HS"]',
 '["Changer l\'huile de boîte.","Tester les électrovannes.","Diagnostiquer le TCU."]'),

# ═══════════════════════════════════════════════════════════════════════════
# SUZUKI — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1100","SUZUKI","medium","MAF sensor circuit fault","Circuit débitmètre — défaut",
 '["Débitmètre encrassé","Connecteur lâche","Filtre à air colmaté"]',
 '["Nettoyer le débitmètre.","Vérifier le connecteur.","Remplacer le filtre."]'),
("P1250","SUZUKI","high","Fuel pressure solenoid valve","Electrovanne pression carburant — défaut",
 '["Electrovanne HS","Câblage endommagé","ECM défaillant"]',
 '["Tester l\'électrovanne.","Vérifier le câblage.","Contrôler l\'ECM."]'),
("P1410","SUZUKI","medium","EGR valve circuit fault","Circuit vanne EGR — défaut",
 '["Vanne EGR HS ou encrassée","Câblage endommagé","ECM défaillant"]',
 '["Nettoyer la vanne EGR.","Vérifier le câblage.","Contrôler l\'ECM."]'),
("P1450","SUZUKI","medium","Barometric pressure sensor circuit","Circuit capteur pression atmosphérique — défaut",
 '["Capteur BARO HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le capteur BARO.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1500","SUZUKI","medium","Starter signal circuit","Circuit signal démarreur — défaut",
 '["Câblage signal démarreur endommagé","Commutateur d\'allumage HS","ECM défaillant"]',
 '["Vérifier le signal au démarrage.","Tester le commutateur.","Contrôler l\'ECM."]'),
("P1600","SUZUKI","high","ECU power supply fault","Alimentation ECU — défaut",
 '["Fusible ECU claqué","Câblage endommagé","Batterie faible"]',
 '["Vérifier les fusibles ECU.","Contrôler la batterie.","Tester le câblage alimentation."]'),

# ═══════════════════════════════════════════════════════════════════════════
# NISSAN / INFINITI — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1105","NISSAN","medium","MAP/BARO switch solenoid valve","Solénoïde commutation MAP/BARO — défaut",
 '["Solénoïde HS","Durite de dépression percée","ECM défaillant"]',
 '["Inspecter les durites.","Tester le solénoïde.","Diagnostiquer l\'ECM."]'),
("P1126","NISSAN","medium","Thermostat function","Thermostat — fonction anormale",
 '["Thermostat coincé ouvert","Capteur ECT HS","Fuite circuit refroidissement"]',
 '["Vérifier la montée en température.","Remplacer le thermostat si ne s\'ouvre pas à 88°C.","Contrôler le capteur ECT."]'),
("P1128","NISSAN","medium","Long term fuel trim lean B1","Apprentissage carburant pauvre — B1",
 '["Fuite d\'air admission","MAF encrassé","Injecteurs bouché"]',
 '["Inspecter l\'admission.","Nettoyer le MAF.","Tester les injecteurs."]'),
("P1148","NISSAN","medium","Closed loop control fault bank 1","Boucle fermée défaillante — B1",
 '["Sonde O2 amont HS","ECM défaillant","Fuite avant sonde"]',
 '["Vérifier la sonde O2 amont.","Inspecter les fuites échappement.","Diagnostiquer l\'ECM."]'),
("P1165","NISSAN","medium","Swirl control valve actuator circuit","Circuit actionneur volet tourbillon — défaut",
 '["Actionneur volet SWIRL HS","Câblage endommagé","ECM défaillant"]',
 '["Tester l\'actionneur.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1217","NISSAN","high","Engine over temperature","Surchauffe moteur",
 '["Niveau liquide refroidissement bas","Thermostat HS","Ventilateur défaillant","Joint de culasse percé"]',
 '["Vérifier le niveau de liquide.","Contrôler le thermostat.","Tester le ventilateur.","Vérifier la présence d\'huile dans le liquide."]'),
("P1320","NISSAN","high","Ignition signal primary circuit","Signal primaire allumage — défaut",
 '["Module allumage HS","Bobine défectueuse","Câblage haute tension"]',
 '["Tester chaque bobine.","Vérifier les câbles HT.","Remplacer le module si HS."]'),
("P1336","NISSAN","high","Crankshaft position sensor","Capteur position vilebrequin — défaut",
 '["Capteur PMH HS","Roue phonique endommagée","Câblage coupé"]',
 '["Vérifier l\'entrefer.","Tester la résistance.","Inspecter la roue phonique."]'),
("P1400","NISSAN","medium","EGRC-BPT valve","Valve EGRC-BPT — défaut",
 '["Valve EGRC encrassée","Durites bouchées","ECM défaillant"]',
 '["Nettoyer les durites EGRC.","Tester la valve.","Contrôler l\'ECM."]'),
("P1440","NISSAN","medium","EVAP small leak","EVAP — petite fuite",
 '["Bouchon réservoir endommagé","Durite EVAP percée","Electrovanne purge HS"]',
 '["Vérifier le bouchon.","Inspecter les durites.","Tester l\'électrovanne."]'),
("P1490","NISSAN","medium","Vacuum cut bypass valve circuit","Circuit valve bypass vacuum — défaut",
 '["Valve bypass HS","Câblage endommagé","ECM défaillant"]',
 '["Tester la valve bypass.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1564","NISSAN","medium","ASCD steering switch circuit","Circuit commutateur direction ASCD — défaut",
 '["Commutateur régulateur vitesse HS","Câblage endommagé","Module ASCD défaillant"]',
 '["Vérifier le commutateur.","Contrôler le câblage.","Diagnostiquer le module ASCD."]'),
("P1605","NISSAN","high","TCM A/T diagnosis communication line","Ligne communication diagnostic TCM — défaut",
 '["Bus CAN boîte interrompu","TCM défaillant","Câblage CAN BVA"]',
 '["Vérifier le câblage CAN.","Diagnostiquer le TCM.","Tester la résistance CAN (120Ω)."]'),

# ═══════════════════════════════════════════════════════════════════════════
# TESLA — codes spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("CP_a001","TESLA","high","Charge port door stuck","Trappe de charge — bloquée",
 '["Actuateur trappe défaillant","Corps étrangers dans trappe","ECU trappe HS"]',
 '["Redémarrer le véhicule.","Vérifier l\'absence de corps étrangers.","Contacter le service Tesla."]'),
("BMS_a001","TESLA","high","Battery cell over-temperature","Cellule batterie — surchauffe",
 '["Système de refroidissement batterie défaillant","Conditions climatiques extrêmes","Charge rapide répétée"]',
 '["Arrêter la charge.","Laisser le véhicule refroidir.","Contacter Tesla si récurrent."]'),
("BMS_a002","TESLA","high","Battery cell under-voltage","Cellule batterie — sous-tension",
 '["Cellule dégradée","Décharge profonde","Vieillissement batterie"]',
 '["Charger immédiatement le véhicule.","Éviter les décharges profondes (<10%).","Contacter Tesla pour diagnostic batterie."]'),
("BMS_a003","TESLA","medium","Battery cooling system fault","Système refroidissement batterie — défaut",
 '["Pompe liquide refroidissement batterie HS","Fuite circuit refroidissement","Capteur température HS"]',
 '["Vérifier le niveau liquide refroidissement.","Inspecter les durites.","Contacter Tesla service."]'),
("DI_a001","TESLA","high","Drive inverter fault","Onduleur de traction — défaut",
 '["Transistors IGBT dégradés","Surchauffe onduleur","Problème logiciel"]',
 '["Redémarrer le véhicule.","Éviter la charge rapide temporairement.","Contacter Tesla en urgence."]'),
("DI_a002","TESLA","high","Motor stator over-temperature","Stator moteur — surchauffe",
 '["Conduite sportivement intensive","Système refroidissement moteur défaillant","Capteur température HS"]',
 '["Laisser le moteur refroidir.","Éviter les accélérations répétées.","Contacter Tesla si récurrent."]'),
("VCFRONT_a001","TESLA","medium","Charge port latch fault","Verrou trappe charge — défaut",
 '["Actuateur verrou HS","Câblage endommagé","Humidité dans le connecteur"]',
 '["Redémarrer le véhicule.","Vérifier le connecteur de charge.","Contacter Tesla service."]'),
("BMS_a004","TESLA","medium","High voltage interlock fault","Verrouillage haute tension — défaut",
 '["Connecteur HV mal inséré","Câble HV endommagé","Module HVIL défaillant"]',
 '["Ne pas ouvrir les connecteurs HV.","Contacter Tesla en urgence.","Ne pas conduire le véhicule."]'),
("EPAS_a001","TESLA","high","Electric power steering fault","Direction assistée électrique — défaut",
 '["Module EPS HS","Capteur angle volant défaillant","Alimentation EPS coupée"]',
 '["Redémarrer le véhicule.","Vérifier la batterie 12V.","Contacter Tesla si persistant."]'),
("REGEN_a001","TESLA","medium","Regenerative braking reduced","Freinage régénératif — réduit",
 '["Batterie froide (<15°C)","Batterie chargée >95%","Défaut système de freinage"]',
 '["Chauffer le véhicule.","Attendre que la batterie soit entre 20-90%.","Contacter Tesla si persistant en conditions normales."]'),

# ═══════════════════════════════════════════════════════════════════════════
# SAAB — codes spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1106","SAAB","medium","MAP sensor intermittent","Capteur MAP — signal intermittent",
 '["Capteur MAP lâche","Durite de dépression fissurée","ECM défaillant"]',
 '["Inspecter les durites.","Fixer le capteur MAP.","Remplacer si intermittent."]'),
("P1171","SAAB","high","Fuel system lean bank 1","Mélange trop pauvre — B1",
 '["Fuite d\'air admission","MAF défaillant","Injecteurs bouché"]',
 '["Inspecter l\'admission.","Nettoyer le MAF.","Tester les injecteurs."]'),
("P1300","SAAB","high","Ignition coil module fault","Module bobine allumage — défaut",
 '["Module allumage DI cassette HS","Câble haute tension défaillant","Bougie usée"]',
 '["Remplacer la cassette allumage DI.","Vérifier les câbles HT.","Remplacer les bougies."]'),
("P1312","SAAB","high","Ion sensing module fault","Module détection ionisation — défaut",
 '["Cassette allumage DI défaillante","Bougie encrassée","ECM défaillant"]',
 '["Remplacer la cassette DI.","Remplacer les bougies.","Contrôler l\'ECM."]'),
("P1395","SAAB","medium","Secondary air injection valve circuit","Circuit valve injection air secondaire — défaut",
 '["Valve injection air HS","Câblage endommagé","Pompe d\'air HS"]',
 '["Tester la valve.","Vérifier le câblage.","Tester la pompe d\'air."]'),
("P1560","SAAB","high","Cruise control system fault","Système régulateur vitesse — défaut",
 '["Commutateur régulateur HS","Actuateur papillon HS","ECM défaillant"]',
 '["Tester le commutateur régulateur.","Vérifier l\'actionneur.","Diagnostiquer l\'ECM."]'),
("P1622","SAAB","high","Immobiliser — ECM not authenticated","Antidémarrage — ECM non authentifié",
 '["ECM remplacé sans programmation","Clé non reconnue","IMMO HS"]',
 '["Utiliser outil Tech2 pour programmer.","Tester avec clé originale.","Contacter un spécialiste Saab."]'),

# ═══════════════════════════════════════════════════════════════════════════
# JAGUAR / LAND ROVER — P1xxx spécifiques
# ═══════════════════════════════════════════════════════════════════════════
("P1000","JAGUAR","low","On-board diagnostics not ready","OBD non prêt — tests incomplets",
 '["Batterie récemment déconnectée","Cycle de conduite incomplet","Calculateur remplacé"]',
 '["Effectuer un cycle de conduite (mixte).","Attendre extinction du voyant.","Vérifier absence de codes actifs."]'),
("P1105","JAGUAR","medium","MAP sensor circuit","Circuit capteur MAP — défaut",
 '["Capteur MAP HS","Durite de dépression percée","ECM HS"]',
 '["Inspecter les durites.","Tester le capteur MAP.","Diagnostiquer l\'ECM."]'),
("P1111","JAGUAR","medium","IAT sensor circuit low","Capteur température air — circuit faible",
 '["Capteur IAT HS","Câblage endommagé","Court-circuit masse"]',
 '["Tester la résistance capteur.","Vérifier le câblage.","Remplacer si HS."]'),
("P1131","JAGUAR","medium","O2 sensor bank 1 sensor 1 lean","Sonde O2 B1 S1 — mélange pauvre",
 '["Fuite d\'air admission","MAF encrassé","Injecteurs bouché"]',
 '["Inspecter l\'admission.","Nettoyer le MAF.","Tester les injecteurs."]'),
("P1132","JAGUAR","medium","O2 sensor bank 1 sensor 1 rich","Sonde O2 B1 S1 — mélange riche",
 '["Injecteurs qui fuient","Pression carburant élevée","MAF défaillant"]',
 '["Tester les injecteurs.","Mesurer la pression carburant.","Remplacer le MAF."]'),
("P1168","JAGUAR","medium","Fuel system rich bank 2","Mélange riche — B2",
 '["Injecteurs B2 qui fuient","Sonde O2 B2 défaillante","Calculateur HS"]',
 '["Tester les injecteurs B2.","Remplacer la sonde O2 B2 si HS.","Diagnostiquer le calculateur."]'),
("P1171","JAGUAR","high","Fuel system lean bank 1","Mélange pauvre — B1",
 '["Pression carburant basse","Injecteurs B1 bouché","Fuite d\'air"]',
 '["Mesurer la pression carburant.","Tester les injecteurs.","Inspecter l\'admission."]'),
("P1200","JAGUAR","high","Injector circuit fault","Circuit injecteurs — défaut",
 '["Câblage injecteur coupé","Relais injection HS","ECM défaillant"]',
 '["Vérifier le relais injection.","Tester le câblage injecteurs.","Diagnostiquer l\'ECM."]'),
("P1260","JAGUAR","high","Theft detected — engine disabled","Vol détecté — moteur immobilisé",
 '["PATS/PATS2 défaillant","Transpondeur clé HS","PCM non synchronisé"]',
 '["Utiliser la clé de secours.","Vérifier l\'antenne PATS.","Resynchroniser via outil Land Rover."]'),
("P1401","JAGUAR","medium","EGR temperature sensor circuit","Circuit capteur température EGR — défaut",
 '["Capteur température EGR HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le capteur.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1500","JAGUAR","medium","Vehicle speed sensor circuit fault","Circuit capteur vitesse — défaut",
 '["Capteur VSS HS","Câblage ABS endommagé","Calculateur ABS HS"]',
 '["Vérifier le capteur VSS.","Inspecter le câblage ABS.","Diagnostiquer le calculateur ABS."]'),
("P1601","JAGUAR","high","ECM — NVRAM write error","ECM — erreur écriture NVRAM",
 '["Surtension lors d\'écriture","ECM défaillant","Batterie instable"]',
 '["Vérifier la stabilité de la batterie.","Effacer les codes.","Remplacer l\'ECM si persistant."]'),
("P1635","JAGUAR","high","5V reference circuit fault","Circuit référence 5V — défaut",
 '["Court-circuit sur capteur","Câblage 5V endommagé","ECM défaillant"]',
 '["Identifier le capteur en court-circuit (déconnecter un par un).","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),

# ═══════════════════════════════════════════════════════════════════════════
# FORD / LINCOLN — codes supplémentaires
# ═══════════════════════════════════════════════════════════════════════════
("P1000","FORD","low","OBD system readiness not complete","Préparation système OBD incomplète",
 '["Batterie déconnectée récemment","Cycle de conduite incomplet","PCM remplacé"]',
 '["Effectuer un cycle de conduite complet.","Attendre l\'extinction du voyant."]'),
("P1100","FORD","medium","MAF sensor intermittent","Débitmètre — signal intermittent",
 '["Débitmètre HS","Connecteur lâche","Filtre à air colmaté"]',
 '["Nettoyer le débitmètre.","Vérifier le connecteur.","Remplacer le filtre."]'),
("P1120","FORD","medium","TP sensor out of range low","Capteur TPS — hors plage bas",
 '["Corps papillon encrassé","Capteur TPS HS","Câblage endommagé"]',
 '["Nettoyer le corps papillon.","Tester le TPS.","Remplacer si HS."]'),
("P1121","FORD","medium","TP sensor inconsistent with MAF","Capteur TPS — incohérence avec MAF",
 '["TPS ou MAF défaillant","Câblage endommagé","PCM défaillant"]',
 '["Vérifier le TPS et le MAF.","Contrôler le câblage.","Diagnostiquer le PCM."]'),
("P1130","FORD","medium","O2 sensor insufficient switching B1 S1","Sonde O2 — commutation insuffisante B1 S1",
 '["Sonde O2 empoisonnée","Fuite d\'air avant sonde","Carburant de mauvaise qualité"]',
 '["Vérifier les fuites d\'air.","Remplacer la sonde O2 si vieille.","Utiliser du carburant propre."]'),
("P1131","FORD","medium","O2 sensor lean B1 S1","Sonde O2 — mélange pauvre B1 S1",
 '["Fuite admission","Injecteurs bouché","Pompe carburant faible"]',
 '["Inspecter l\'admission.","Tester les injecteurs.","Mesurer la pression carburant."]'),
("P1132","FORD","medium","O2 sensor rich B1 S1","Sonde O2 — mélange riche B1 S1",
 '["Injecteurs qui fuient","Pression carburant excessive","MAF déréglé"]',
 '["Tester les injecteurs.","Mesurer la pression carburant.","Nettoyer/remplacer le MAF."]'),
("P1233","FORD","high","Fuel pump driver module off-line","Module commande pompe carburant — hors ligne",
 '["Module FP Driver HS","Câblage module endommagé","Fusible module claqué"]',
 '["Vérifier le fusible du module.","Tester le module (alimentation + signal).","Remplacer si HS."]'),
("P1260","FORD","high","Theft detected — vehicle immobilised","Vol détecté — véhicule immobilisé",
 '["PATS défaillant","Clé transponder HS","Antenne PATS défaillante"]',
 '["Utiliser la clé de secours.","Vérifier l\'antenne PATS.","Reprogrammer les clés."]'),
("P1270","FORD","medium","Engine RPM or speed limiter reached","Limiteur régime/vitesse atteint",
 '["Normal si limiteur actif","Capteur vitesse HS","PCM défaillant"]',
 '["Vérifier si limiteur intentionnel.","Contrôler le capteur vitesse.","Diagnostiquer le PCM si anormal."]'),
("P1380","FORD","medium","Variable cam timing solenoid circuit B1","Circuit solénoïde calage variable B1 — défaut",
 '["Solénoïde VCT HS","Huile moteur sale","Câblage endommagé"]',
 '["Changer l\'huile moteur.","Tester le solénoïde VCT.","Vérifier le câblage."]'),
("P1381","FORD","medium","Variable cam timing over-advanced B1","Calage variable trop avancé — B1",
 '["Solénoïde VCT bloqué","Chaîne distribution étirée","Huile dégradée"]',
 '["Changer l\'huile.","Inspecter la chaîne.","Tester le solénoïde."]'),
("P1400","FORD","medium","DPFE sensor circuit low","Circuit capteur DPFE — signal faible",
 '["Capteur DPFE HS","Tubes de pression bouchés","Câblage endommagé"]',
 '["Nettoyer les tubes de pression DPFE.","Tester le capteur.","Remplacer si HS."]'),
("P1401","FORD","medium","DPFE sensor circuit high","Circuit capteur DPFE — signal élevé",
 '["Capteur DPFE HS","Court-circuit alimentation","Câblage endommagé"]',
 '["Vérifier le câblage.","Tester le capteur DPFE.","Remplacer si HS."]'),
("P1405","FORD","medium","DPFE sensor upstream hose off","Tuyau amont capteur DPFE déconnecté",
 '["Tuyau déconnecté ou percé","Joint tuyau usé"]',
 '["Reconnecter/remplacer le tuyau amont DPFE.","Vérifier l\'étanchéité."]'),
("P1406","FORD","medium","DPFE sensor downstream hose off","Tuyau aval capteur DPFE déconnecté",
 '["Tuyau déconnecté ou percé","Joint usé"]',
 '["Reconnecter/remplacer le tuyau aval DPFE.","Vérifier l\'étanchéité."]'),
("P1450","FORD","medium","EVAP unable to bleed up fuel tank vacuum","EVAP — incapable d\'équilibrer dépression réservoir",
 '["Electrovanne EVAP HS","Durite EVAP bouchée","Bouchon réservoir HS"]',
 '["Tester l\'électrovanne EVAP.","Inspecter les durites.","Remplacer le bouchon."]'),
("P1451","FORD","medium","EVAP vent solenoid circuit fault","Circuit solénoïde évent EVAP — défaut",
 '["Solénoïde évent HS","Câblage endommagé","PCM défaillant"]',
 '["Tester le solénoïde évent.","Vérifier le câblage.","Diagnostiquer le PCM."]'),
("P1516","FORD","high","Throttle actuator control module fault","Module commande actionneur papillon — défaut",
 '["Module TAC HS","Corps papillon encrassé","Câblage endommagé"]',
 '["Nettoyer le corps papillon.","Tester le module TAC.","Remplacer si HS."]'),
("P1636","FORD","high","Inductive signature chip communication fault","Communication puce signature inductive — défaut",
 '["Transpondeur clé HS","Module PATS HS","Câblage défaillant"]',
 '["Tester avec clé originale.","Vérifier le module PATS.","Reprogrammer les clés."]'),

# ═══════════════════════════════════════════════════════════════════════════
# SUBARU — codes supplémentaires
# ═══════════════════════════════════════════════════════════════════════════
("P1086","SUBARU","medium","Tumble generator valve 2 circuit","Circuit valve générateur turbulence 2 — défaut",
 '["Valve TGVS HS","Moteur électrique valve HS","Câblage endommagé"]',
 '["Tester la valve TGV.","Vérifier le moteur électrique.","Contrôler le câblage."]'),
("P1088","SUBARU","medium","Tumble generator valve 1 circuit","Circuit valve générateur turbulence 1 — défaut",
 '["Valve TGV1 HS","Câblage endommagé","ECM défaillant"]',
 '["Tester la valve.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1090","SUBARU","medium","Tumble generator motor 1 high","Moteur valve turbulence 1 — signal élevé",
 '["Moteur TGV1 HS","Court-circuit alimentation","ECM défaillant"]',
 '["Tester la résistance moteur TGV.","Vérifier le câblage.","Remplacer si HS."]'),
("P1092","SUBARU","medium","Tumble generator motor 2 high","Moteur valve turbulence 2 — signal élevé",
 '["Moteur TGV2 HS","Court-circuit","ECM défaillant"]',
 '["Tester la résistance.","Vérifier le câblage.","Remplacer si HS."]'),
("P1094","SUBARU","medium","Tumble generator motor 1 low","Moteur valve turbulence 1 — signal faible",
 '["Câblage moteur coupé","Moteur HS","ECM défaillant"]',
 '["Vérifier le câblage.","Tester le moteur.","Diagnostiquer l\'ECM."]'),
("P1096","SUBARU","medium","Tumble generator motor 2 low","Moteur valve turbulence 2 — signal faible",
 '["Câblage moteur coupé","Moteur HS","ECM défaillant"]',
 '["Vérifier le câblage.","Tester le moteur.","Diagnostiquer l\'ECM."]'),
("P1110","SUBARU","medium","Intake air temperature sensor 2 low","Capteur température air 2 — signal faible",
 '["Capteur IAT2 HS","Câblage endommagé","Court-circuit masse"]',
 '["Tester la résistance capteur.","Vérifier le câblage.","Remplacer si HS."]'),
("P1130","SUBARU","medium","Front O2 sensor range B1","Plage sonde O2 avant — B1",
 '["Sonde O2 empoisonnée","Fuite d\'échappement avant","Carburant contaminé"]',
 '["Inspecter l\'échappement.","Remplacer la sonde si vieille.","Vérifier la qualité du carburant."]'),
("P1134","SUBARU","medium","Front O2 sensor response B1","Réponse sonde O2 avant — B1",
 '["Sonde O2 en fin de vie","Chauffage sonde HS","Carburant dégradé"]',
 '["Tester le chauffage sonde.","Remplacer la sonde O2."]'),
("P1400","SUBARU","medium","Fuel tank pressure sensor circuit","Circuit capteur pression réservoir — défaut",
 '["Capteur pression réservoir HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le capteur.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1410","SUBARU","medium","Secondary air injection solenoid","Solénoïde injection air secondaire — défaut",
 '["Solénoïde HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1491","SUBARU","medium","EGR valve solenoid circuit","Circuit solénoïde vanne EGR — défaut",
 '["Solénoïde EGR HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde EGR.","Vérifier le câblage.","Contrôler l\'ECM."]'),

# ═══════════════════════════════════════════════════════════════════════════
# MAZDA — codes supplémentaires
# ═══════════════════════════════════════════════════════════════════════════
("P1086","MAZDA","medium","Swirl shutter valve 2 motor circuit","Circuit moteur volet tourbillon 2 — défaut",
 '["Moteur volet HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le moteur.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1088","MAZDA","medium","Swirl shutter valve 1 motor circuit","Circuit moteur volet tourbillon 1 — défaut",
 '["Moteur volet 1 HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le moteur.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1120","MAZDA","medium","TP sensor circuit range low","Plage capteur TPS — signal bas",
 '["Capteur TPS HS","Corps papillon encrassé","Câblage endommagé"]',
 '["Nettoyer le corps papillon.","Tester le TPS.","Remplacer si HS."]'),
("P1121","MAZDA","medium","TP sensor circuit range high","Plage capteur TPS — signal élevé",
 '["Court-circuit alimentation TPS","Capteur HS","ECM défaillant"]',
 '["Vérifier l\'alimentation.","Tester le capteur.","Diagnostiquer l\'ECM."]'),
("P1187","MAZDA","high","Fuel trim adaptive lean B1","Correction adaptative pauvre — B1",
 '["MAF encrassé","Fuite d\'air","Injecteurs bouché"]',
 '["Nettoyer le MAF.","Inspecter l\'admission.","Tester les injecteurs."]'),
("P1250","MAZDA","high","Pressure regulator control solenoid","Solénoïde régulateur pression — défaut",
 '["Solénoïde HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1345","MAZDA","high","SGC — crankshaft/camshaft correlation","Corrélation vilebrequin/arbre à cames",
 '["Courroie distribution sautée","Capteur PMH HS","Capteur arbre à cames HS"]',
 '["Vérifier le calage distribution.","Tester les capteurs.","Inspecter la courroie."]'),
("P1410","MAZDA","medium","EGR valve circuit fault","Circuit vanne EGR — défaut",
 '["Vanne EGR encrassée","Câblage endommagé","ECM défaillant"]',
 '["Nettoyer la vanne EGR.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1443","MAZDA","medium","EVAP purge control solenoid","Solénoïde purge EVAP — défaut",
 '["Solénoïde purge HS","Câblage endommagé","ECM défaillant"]',
 '["Tester le solénoïde purge.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),
("P1521","MAZDA","medium","Variable intake air system fault","Système admission variable — défaut",
 '["Actionneur VICS HS","Câblage endommagé","ECM défaillant"]',
 '["Tester l\'actionneur VICS.","Vérifier le câblage.","Diagnostiquer l\'ECM."]'),

]

def insert_codes(codes):
    conn = sqlite3.connect(DB)
    existing = set(
        row[0] + "|" + row[1]
        for row in conn.execute("SELECT code, brand FROM codes")
    )
    inserted = 0
    skipped = 0
    for row in codes:
        code, brand, sev, title_en, title_fr, causes, steps = row
        key = code + "|" + brand
        if key in existing:
            skipped += 1
            continue
        conn.execute(
            "INSERT INTO codes (code, brand, severity, title, causes, steps, title_fr) VALUES (?,?,?,?,?,?,?)",
            (code, brand, sev, title_fr, causes, steps, title_fr)
        )
        existing.add(key)
        inserted += 1
    conn.commit()
    conn.close()
    return inserted, skipped

if __name__ == "__main__":
    ins, sk = insert_codes(NEW_CODES)
    conn = sqlite3.connect(DB)
    total = conn.execute("SELECT COUNT(*) FROM codes").fetchone()[0]
    conn.close()
    print(f"✅ {ins} codes ajoutés, {sk} ignorés (doublons)")
    print(f"📊 Total base : {total} codes")
